order = -1
copyright_name = "Your Name"
name = "Archival"
home_title = "HI!"
author = "Archival"
video_url = "https://archival-uploads.jesseditson.com/example.mp4"
description = "A simple video presentation template."
